/* --- DICTIONNAIRE CYBER-SPY (Undercover) FR/EN --- */

const wordPairs = [
    // --- MANGAS & ANIMÉS ---
    { category: "mangas", fr: ["Picasso", "Matisse"], en: ["Picasso", "Matisse"] },
    { category: "mangas", fr: ["Nikola Tesla", "Elon Musk"], en: ["Nikola Tesla", "Elon Musk"] },
    { category: "mangas", fr: ["Freezer", "Frigo"], en: ["Freezer", "Fridge"] },
    { category: "mangas", fr: ["Naruto", "Feunard"], en: ["Naruto", "Ninetales"] },
    { category: "mangas", fr: ["Goku", "Superman"], en: ["Goku", "Superman"] },
    { category: "mangas", fr: ["Kira", "L"], en: ["Kira", "L"] },
    { category: "mangas", fr: ["Luffy", "Jack Sparrow"], en: ["Luffy", "Jack Sparrow"] },
    { category: "mangas", fr: ["Titans", "Géants"], en: ["Titans", "Giants"] },
    { category: "mangas", fr: ["Saitama", "Krilin"], en: ["Saitama", "Krillin"] },
    { category: "mangas", fr: ["Tortue Géniale", "Jiraiya"], en: ["Master Roshi", "Jiraiya"] },
    { category: "mangas", fr: ["Eren Jäger", "Godzilla"], en: ["Eren Yeager", "Godzilla"] },
    { category: "mangas", fr: ["Pikachu", "Évoli"], en: ["Pikachu", "Eevee"] },
    { category: "mangas", fr: ["Guts", "Jon Snow"], en: ["Guts", "Jon Snow"] },
    { category: "mangas", fr: ["Vegeta", "Sasuke"], en: ["Vegeta", "Sasuke"] },
    { category: "mangas", fr: ["Totoro", "Mickey"], en: ["Totoro", "Mickey"] },
    { category: "mangas", fr: ["Katana", "Épée"], en: ["Katana", "Sword"] },
    { category: "mangas", fr: ["Sharingan", "Byakugan"], en: ["Sharingan", "Byakugan"] },
    { category: "mangas", fr: ["Ninja", "Samouraï"], en: ["Ninja", "Samurai"] },
    { category: "mangas", fr: ["Hunter x Hunter", "One Piece"], en: ["Hunter x Hunter", "One Piece"] },
    { category: "mangas", fr: ["Manga", "Comics"], en: ["Manga", "Comics"] },
    { category: "mangas", fr: ["Cosplay", "Déguisement"], en: ["Cosplay", "Costume"] },
    { category: "mangas", fr: ["Kamehameha", "Rasengan"], en: ["Kamehameha", "Rasengan"] },

    // --- POP CULTURE & FILMS ---
    { category: "pop_culture", fr: ["Dumbledore", "Gandalf"], en: ["Dumbledore", "Gandalf"] },
    { category: "pop_culture", fr: ["Batman", "Iron Man"], en: ["Batman", "Iron Man"] },
    { category: "pop_culture", fr: ["Néo", "John Wick"], en: ["Neo", "John Wick"] },
    { category: "pop_culture", fr: ["Dark Vador", "Kylo Ren"], en: ["Darth Vader", "Kylo Ren"] },
    { category: "pop_culture", fr: ["Mario", "Luigi"], en: ["Mario", "Luigi"] },
    { category: "pop_culture", fr: ["Gollum", "Dobby"], en: ["Gollum", "Dobby"] },
    { category: "pop_culture", fr: ["Dracula", "Edward Cullen"], en: ["Dracula", "Edward Cullen"] },
    { category: "pop_culture", fr: ["Terminator", "Cyborg"], en: ["Terminator", "Cyborg"] },
    { category: "pop_culture", fr: ["Sauron", "Voldemort"], en: ["Sauron", "Voldemort"] },
    { category: "pop_culture", fr: ["Joker", "Bouffon Vert"], en: ["Joker", "Green Goblin"] },
    { category: "pop_culture", fr: ["Sonic", "Flash"], en: ["Sonic", "Flash"] },
    { category: "pop_culture", fr: ["Poudlard", "Narnia"], en: ["Hogwarts", "Narnia"] },
    { category: "pop_culture", fr: ["Spider-Man", "Venom"], en: ["Spider-Man", "Venom"] },
    { category: "pop_culture", fr: ["Luke Skywalker", "Harry Potter"], en: ["Luke Skywalker", "Harry Potter"] },
    { category: "pop_culture", fr: ["Homer Simpson", "Peter Griffin"], en: ["Homer Simpson", "Peter Griffin"] },
    { category: "pop_culture", fr: ["Avengers", "Justice League"], en: ["Avengers", "Justice League"] },
    { category: "pop_culture", fr: ["Groot", "Chewbacca"], en: ["Groot", "Chewbacca"] },
    { category: "pop_culture", fr: ["Thanos", "Palpatine"], en: ["Thanos", "Palpatine"] },
    { category: "pop_culture", fr: ["James Bond", "Ethan Hunt"], en: ["James Bond", "Ethan Hunt"] },
    { category: "pop_culture", fr: ["Indiana Jones", "Lara Croft"], en: ["Indiana Jones", "Lara Croft"] },
    { category: "pop_culture", fr: ["Sherlock Holmes", "Hercule Poirot"], en: ["Sherlock Holmes", "Hercule Poirot"] },
    { category: "pop_culture", fr: ["Disney", "Pixar"], en: ["Disney", "Pixar"] },
    { category: "pop_culture", fr: ["Matrix", "Inception"], en: ["Matrix", "Inception"] },
    { category: "pop_culture", fr: ["King Kong", "Jurassic Park"], en: ["King Kong", "Jurassic Park"] },

    // --- HISTOIRE & MÉTIERS ---
    { category: "histoire_metiers", fr: ["Albert Einstein", "Isaac Newton"], en: ["Albert Einstein", "Isaac Newton"] },
    { category: "histoire_metiers", fr: ["Léonard de Vinci", "Donatello"], en: ["Da Vinci", "Donatello"] },
    { category: "histoire_metiers", fr: ["Mozart", "Beethoven"], en: ["Mozart", "Beethoven"] },
    { category: "histoire_metiers", fr: ["Steve Jobs", "Pomme"], en: ["Steve Jobs", "Apple"] },
    { category: "histoire_metiers", fr: ["Zuckerberg", "Lézard"], en: ["Zuckerberg", "Lizard"] },
    { category: "histoire_metiers", fr: ["Napoléon", "Jules César"], en: ["Napoleon", "Julius Caesar"] },
    { category: "histoire_metiers", fr: ["Cléopâtre", "Nefertiti"], en: ["Cleopatra", "Nefertiti"] },
    { category: "histoire_metiers", fr: ["Pompier", "Policier"], en: ["Firefighter", "Police Officer"] },
    { category: "histoire_metiers", fr: ["Astronaute", "Pilote"], en: ["Astronaut", "Pilot"] },
    { category: "histoire_metiers", fr: ["Espion", "Détective"], en: ["Spy", "Detective"] },
    { category: "histoire_metiers", fr: ["Pirate", "Corsaire"], en: ["Pirate", "Privateer"] },
    { category: "histoire_metiers", fr: ["Pharaon", "Empereur"], en: ["Pharaoh", "Emperor"] },
    { category: "histoire_metiers", fr: ["Boulanger", "Cuisinier"], en: ["Baker", "Cook"] },
    { category: "histoire_metiers", fr: ["Gladiateur", "Mousquetaire"], en: ["Gladiator", "Musketeer"] },

    // --- JEUX VIDÉO, TECH & WEB ---
    { category: "tech_gaming", fr: ["PlayStation", "Xbox"], en: ["PlayStation", "Xbox"] },
    { category: "tech_gaming", fr: ["Minecraft", "Lego"], en: ["Minecraft", "Lego"] },
    { category: "tech_gaming", fr: ["Zelda", "Peach"], en: ["Zelda", "Peach"] },
    { category: "tech_gaming", fr: ["Spotify", "Deezer"], en: ["Spotify", "Deezer"] },
    { category: "tech_gaming", fr: ["Twitch", "YouTube"], en: ["Twitch", "YouTube"] },
    { category: "tech_gaming", fr: ["Google", "Wikipedia"], en: ["Google", "Wikipedia"] },
    { category: "tech_gaming", fr: ["Discord", "Skype"], en: ["Discord", "Skype"] },
    { category: "tech_gaming", fr: ["TikTok", "Instagram"], en: ["TikTok", "Instagram"] },
    { category: "tech_gaming", fr: ["Clavier", "Manette"], en: ["Keyboard", "Controller"] },
    { category: "tech_gaming", fr: ["Netflix", "Prime Video"], en: ["Netflix", "Prime Video"] },
    { category: "tech_gaming", fr: ["PC", "Mac"], en: ["PC", "Mac"] },
    { category: "tech_gaming", fr: ["Android", "iOS"], en: ["Android", "iOS"] },
    { category: "tech_gaming", fr: ["Mario Kart", "Crash Team Racing"], en: ["Mario Kart", "Crash Team Racing"] },
    { category: "tech_gaming", fr: ["GTA", "Red Dead Redemption"], en: ["GTA", "Red Dead Redemption"] },
    { category: "tech_gaming", fr: ["Pokemon", "Digimon"], en: ["Pokemon", "Digimon"] },
    { category: "tech_gaming", fr: ["Souris", "Trackpad"], en: ["Mouse", "Trackpad"] },
    { category: "tech_gaming", fr: ["Clé USB", "Disque Dur"], en: ["USB Drive", "Hard Drive"] },
    { category: "tech_gaming", fr: ["Pac-Man", "Tetris"], en: ["Pac-Man", "Tetris"] },
    { category: "tech_gaming", fr: ["Nintendo", "Sega"], en: ["Nintendo", "Sega"] },
    { category: "tech_gaming", fr: ["Wifi", "Bluetooth"], en: ["Wifi", "Bluetooth"] },

    // --- NOURRITURE & BOISSONS ---
    { category: "food", fr: ["Pizza", "Quiche"], en: ["Pizza", "Quiche"] },
    { category: "food", fr: ["Coca-Cola", "Pepsi"], en: ["Coca-Cola", "Pepsi"] },
    { category: "food", fr: ["Café", "Thé"], en: ["Coffee", "Tea"] },
    { category: "food", fr: ["Croissant", "Chocolatine"], en: ["Croissant", "Pain au chocolat"] },
    { category: "food", fr: ["Kebab", "Tacos"], en: ["Kebab", "Tacos"] },
    { category: "food", fr: ["Sushi", "Maki"], en: ["Sushi", "Maki"] },
    { category: "food", fr: ["Ketchup", "Mayonnaise"], en: ["Ketchup", "Mayonnaise"] },
    { category: "food", fr: ["Bière", "Cidre"], en: ["Beer", "Cider"] },
    { category: "food", fr: ["Hamburger", "Cheeseburger"], en: ["Hamburger", "Cheeseburger"] },
    { category: "food", fr: ["Beurre", "Margarine"], en: ["Butter", "Margarine"] },
    { category: "food", fr: ["Pâtes", "Riz"], en: ["Pasta", "Rice"] },
    { category: "food", fr: ["Crêpe", "Gaufre"], en: ["Crepe", "Waffle"] },
    { category: "food", fr: ["Frite", "Chips"], en: ["French Fries", "Potato Chips"] },
    { category: "food", fr: ["Chocolat", "Nutella"], en: ["Chocolate", "Nutella"] },
    { category: "food", fr: ["Moutarde", "Sauce Tomate"], en: ["Mustard", "Tomato Sauce"] },
    { category: "food", fr: ["Lait", "Lait d'Amande"], en: ["Milk", "Almond Milk"] },
    { category: "food", fr: ["Pomme", "Poire"], en: ["Apple", "Pear"] },
    { category: "food", fr: ["Burger", "Hot-Dog"], en: ["Burger", "Hot-Dog"] },
    { category: "food", fr: ["Bonbon", "Sucre d'orge"], en: ["Candy", "Candy Cane"] },
    { category: "food", fr: ["Kebab", "Libanais"], en: ["Kebab", "Shawarma"] },

    // --- ANIMAUX & NATURE ---
    { category: "nature", fr: ["Tigre", "Lion"], en: ["Tiger", "Lion"] },
    { category: "nature", fr: ["Loup", "Chien"], en: ["Wolf", "Dog"] },
    { category: "nature", fr: ["Aigle", "Faucon"], en: ["Eagle", "Falcon"] },
    { category: "nature", fr: ["Pigeon", "Mouette"], en: ["Pigeon", "Seagull"] },
    { category: "nature", fr: ["Araignée", "Scorpion"], en: ["Spider", "Scorpion"] },
    { category: "nature", fr: ["Crocodile", "Alligator"], en: ["Crocodile", "Alligator"] },
    { category: "nature", fr: ["Océan", "Mer"], en: ["Ocean", "Sea"] },
    { category: "nature", fr: ["Montagne", "Colline"], en: ["Mountain", "Hill"] },
    { category: "nature", fr: ["Neige", "Glace"], en: ["Snow", "Ice"] },
    { category: "nature", fr: ["Glace", "Sorbet"], en: ["Ice Cream", "Sorbet"] },
    { category: "nature", fr: ["Ours", "Panda"], en: ["Bear", "Panda"] },
    { category: "nature", fr: ["Cheval", "Âne"], en: ["Horse", "Donkey"] },
    { category: "nature", fr: ["Serpent", "Lézard"], en: ["Snake", "Lizard"] },
    { category: "nature", fr: ["Aigle", "Corbeau"], en: ["Eagle", "Crow"] },
    { category: "nature", fr: ["Requin", "Dauphin"], en: ["Shark", "Dolphin"] },
    { category: "nature", fr: ["Singe", "Gorille"], en: ["Monkey", "Gorilla"] },
    { category: "nature", fr: ["Soleil", "Étoile"], en: ["Sun", "Star"] },
    { category: "nature", fr: ["Pluie", "Vent"], en: ["Rain", "Wind"] },
    { category: "nature", fr: ["Forêt", "Jungle"], en: ["Forest", "Jungle"] },
    { category: "nature", fr: ["Désert", "Plage"], en: ["Desert", "Beach"] },

    // --- OBJETS DU QUOTIDIEN ---
    { category: "objets", fr: ["Guitare", "Basse"], en: ["Guitar", "Bass"] },
    { category: "objets", fr: ["Piano", "Synthétiseur"], en: ["Piano", "Synthesizer"] },
    { category: "objets", fr: ["Avion", "Hélicoptère"], en: ["Airplane", "Helicopter"] },
    { category: "objets", fr: ["Moto", "Scooter"], en: ["Motorcycle", "Scooter"] },
    { category: "objets", fr: ["Montre", "Horloge"], en: ["Watch", "Clock"] },
    { category: "objets", fr: ["Stylo", "Crayon"], en: ["Pen", "Pencil"] },
    { category: "objets", fr: ["Chaussette", "Gant"], en: ["Sock", "Glove"] },
    { category: "objets", fr: ["Lit", "Canapé"], en: ["Bed", "Sofa"] },
    { category: "objets", fr: ["Savon", "Gel Douche"], en: ["Soap", "Shower Gel"] },
    { category: "objets", fr: ["Brosse à dents", "Cure-dents"], en: ["Toothbrush", "Toothpick"] },
    { category: "objets", fr: ["Verre", "Tasse"], en: ["Glass", "Mug"] },
    { category: "objets", fr: ["Botte", "Sandale"], en: ["Boot", "Sandal"] },
    { category: "objets", fr: ["Manteau", "Pull"], en: ["Coat", "Sweater"] },
    { category: "objets", fr: ["Porte", "Fenêtre"], en: ["Door", "Window"] },
    { category: "objets", fr: ["Télévision", "Cinéma"], en: ["Television", "Cinema"] },
    { category: "objets", fr: ["Shampoing", "Après-shampoing"], en: ["Shampoo", "Conditioner"] },
    { category: "objets", fr: ["Serviette", "Peignoir"], en: ["Towel", "Bathrobe"] },
    { category: "objets", fr: ["Brosse", "Peigne"], en: ["Brush", "Comb"] },
    { category: "objets", fr: ["Livre", "Magazine"], en: ["Book", "Magazine"] },
    { category: "objets", fr: ["Voiture", "Camion"], en: ["Car", "Truck"] },

    // --- PIÈGES ABSURDES & DÉCALÉS ---
    { category: "pieges", fr: ["Baguette", "Sabre Laser"], en: ["Wand", "Lightsaber"] },
    { category: "pieges", fr: ["Chien", "Loup-Garou"], en: ["Dog", "Werewolf"] },
    { category: "pieges", fr: ["Zombie", "Momie"], en: ["Zombie", "Mummy"] },
    { category: "pieges", fr: ["Cthulhu", "Kraken"], en: ["Cthulhu", "Kraken"] },
    { category: "pieges", fr: ["Vampire", "Moustique"], en: ["Vampire", "Mosquito"] },
    { category: "pieges", fr: ["Sorcier", "Magicien"], en: ["Sorcerer", "Magician"] },
    { category: "pieges", fr: ["Avocat", "Juge"], en: ["Lawyer", "Judge"] },
    { category: "pieges", fr: ["Dentiste", "Médecin"], en: ["Dentist", "Doctor"] },
    { category: "pieges", fr: ["Père Noël", "Voleur"], en: ["Santa Claus", "Thief"] },
    { category: "pieges", fr: ["Tracteur", "Tank"], en: ["Tractor", "Tank"] },
    { category: "pieges", fr: ["Baignoire", "Piscine"], en: ["Bathtub", "Swimming Pool"] },
    { category: "pieges", fr: ["Fantôme", "Draps"], en: ["Ghost", "Bed Sheets"] },
    { category: "pieges", fr: ["Micro-onde", "Four"], en: ["Microwave", "Oven"] },
    { category: "pieges", fr: ["Balai", "Aspirateur"], en: ["Broom", "Vacuum Cleaner"] },
    { category: "pieges", fr: ["Oignon", "Ail"], en: ["Onion", "Garlic"] },
    { category: "pieges", fr: ["Moustique", "Mouche"], en: ["Mosquito", "Fly"] },
    { category: "pieges", fr: ["Toilette", "Urinoir"], en: ["Toilet", "Urinal"] },
    { category: "pieges", fr: ["Clown", "Mime"], en: ["Clown", "Mime"] },
    { category: "pieges", fr: ["Cactus", "Hérisson"], en: ["Cactus", "Hedgehog"] },
    { category: "pieges", fr: ["Saucisse", "Merguez"], en: ["Sausage", "Spicy Sausage"] },
    { category: "pieges", fr: ["T-Rex", "Vélociraptor"], en: ["T-Rex", "Velociraptor"] },
    { category: "pieges", fr: ["Extraterrestre", "Astronaute"], en: ["Alien", "Astronaut"] }
];

// Fonction utilitaire pour tirer un mot selon une catégorie
function getRandomPair(category = null) {
    let filtered = category ? wordPairs.filter(w => w.category === category) : wordPairs;
    if (filtered.length === 0) return null;
    return filtered[Math.floor(Math.random() * filtered.length)];
}

console.log(`Dictionnaire 'mots.js' chargé : ${wordPairs.length} paires classées par catégories.`);
