// ==========================================
// BASE DE DONNÉES MUSICALE - CYBER BLIND TEST
// ==========================================

const catalogs = {
    ANIME: [
        { anime: "Naruto", aliases: ["naruto shippuden"], search: "Silhouette Kana-Boon" }, 
        { anime: "Naruto", aliases: ["naruto shippuden"], search: "Blue Bird Ikimonogakari" },
        { anime: "One Piece", aliases: ["onepiece"], search: "We Are! Hiroshi Kitadani" }, 
        { anime: "One Piece", aliases: ["onepiece"], search: "Hope Namie Amuro" },
        { anime: "Bleach", aliases: ["bleachanime"], search: "Asterisk Orange Range" }, 
        { anime: "Bleach", aliases: ["bleachanime"], search: "Ranbu no Melody SID" },
        { anime: "Dragon Ball Z", aliases: ["dbz", "dragonball", "dragon ball"], search: "Cha La Head Cha La Hironobu Kageyama" }, 
        { anime: "Hunter x Hunter", aliases: ["hxh"], search: "Departure Ono Masatoshi" },
        { anime: "Fairy Tail", aliases: ["fairytail"], search: "Snow Fairy FUNKIST" }, 
        { anime: "Gintama", aliases: ["gin tama"], search: "Tougenkyou Alien" },
        { anime: "Fullmetal Alchemist", aliases: ["fma", "full metal alchemist", "fmab", "brotherhood"], search: "Again YUI" },
        { anime: "Death Note", aliases: ["deathnote"], search: "the WORLD Nightmare" },
        { anime: "Death Note", aliases: ["deathnote"], search: "Zetsubou Billy Maximum the Hormone" },
        { anime: "Attack on Titan", aliases: ["snk", "shingeki no kyojin", "aot"], search: "Guren no Yumiya Linked Horizon" }, 
        { anime: "Attack on Titan", aliases: ["snk", "shingeki no kyojin", "aot"], search: "The Rumbling SiM" },
        { anime: "Demon Slayer", aliases: ["kimetsu no yaiba"], search: "Gurenge LiSA" }, 
        { anime: "Jujutsu Kaisen", aliases: ["jjk"], search: "Kaikai Kitan Eve" },
        { anime: "My Hero Academia", aliases: ["mha", "boku no hero academia"], search: "Peace Sign Kenshi Yonezu" }, 
        { anime: "Chainsaw Man", aliases: ["csm"], search: "Kick Back Kenshi Yonezu" },
        { anime: "Oshi no Ko", aliases: ["oshinoko"], search: "Idol Yoasobi" }, 
        { anime: "Spy x Family", aliases: ["spyxfamily", "sxf"], search: "Mixed Nuts Official Hige Dandism" },
        { anime: "Mashle", aliases: ["mashle magic and muscles"], search: "Bling-Bang-Bang-Born Creepy Nuts" }, 
        { anime: "Solo Leveling", aliases: ["sololeveling"], search: "LEveL SawanoHiroyuki" },
        { anime: "Tokyo Revengers", aliases: ["tokyorevengers"], search: "Cry Baby Official Hige Dandism" },
        { anime: "Jojo's Bizarre Adventure", aliases: ["jojo", "jojos", "jjba"], search: "Bloody Stream Coda" },
        { anime: "Jojo's Bizarre Adventure", aliases: ["jojo", "jojos", "jjba"], search: "Il vento d'oro Yugo Kanno" },
        { anime: "Evangelion", aliases: ["neon genesis evangelion", "nge"], search: "A Cruel Angels Thesis Yoko Takahashi" }, 
        { anime: "Cowboy Bebop", aliases: ["cowboybebop"], search: "Tank Seatbelts" },
        { anime: "Great Teacher Onizuka", aliases: ["gto"], search: "Drivers High L'Arc-en-Ciel" }, 
        { anime: "Pokemon", aliases: ["pocket monsters"], search: "Gotta Catch Em All Theme Pokemon" },
        { anime: "Sword Art Online", aliases: ["sao"], search: "Crossing Field LiSA" }, 
        { anime: "Tokyo Ghoul", aliases: ["tokyoghoul"], search: "Unravel TK" },
        { anime: "One Punch Man", aliases: ["opm"], search: "The Hero JAM Project" }, 
        { anime: "Cyberpunk Edgerunners", aliases: ["cyberpunk", "edgerunners"], search: "This Fffire Franz Ferdinand" },
        { anime: "Your Name", aliases: ["kimi no na wa"], search: "Zenzenzense Radwimps" },
        { anime: "Steins;Gate", aliases: ["steins gate"], search: "Hacking to the Gate Kanako Itou" },
        { anime: "Code Geass", aliases: ["codegeass"], search: "Colors Flow" },
        { anime: "Your Lie in April", aliases: ["shigatsu wa kimi no uso"], search: "Hikaru Nara Goose house" },
        { anime: "Moi, quand je me réincarne en Slime", aliases: ["tensura", "that time i got reincarnated as a slime", "slime"], search: "Nameless Story Takuma Terashima" },
        { anime: "Black Clover", aliases: ["blackclover"], search: "Black Rover Vickeblanka" },
        { anime: "Saint Seiya", aliases: ["les chevaliers du zodiaque"], search: "Pegasus Fantasy Make-Up" }, 
        { anime: "Sailor Moon", aliases: ["sailormoon"], search: "Moonlight Densetsu" },
        { anime: "Goldorak", aliases: ["ufo robot grendizer"], search: "Goldorak Noam" }, 
        { anime: "Captain Tsubasa", aliases: ["olive et tom"], search: "Moete Hero" }
    ],
    FILMS: [
        { film: "Interstellar", aliases: ["interstellar"], search: "Cornfield Chase Hans Zimmer" },
        { film: "Inception", aliases: ["inception"], search: "Time Hans Zimmer" },
        { film: "Gladiator", aliases: ["gladiator"], search: "Now We Are Free Hans Zimmer" },
        { film: "The Dark Knight", aliases: ["dark knight", "batman", "the dark knight"], search: "Why So Serious Hans Zimmer" },
        { film: "Le Roi Lion", aliases: ["lion king", "le roi lion"], search: "This Land Hans Zimmer" },
        { film: "Pirates des Caraïbes", aliases: ["pirates of the caribbean", "pirate des caraibes"], search: "He's a Pirate Klaus Badelt" },
        { film: "Dune", aliases: ["dune part 1", "dune part 2", "dune"], search: "Paul's Dream Hans Zimmer" },
        { film: "Le Dernier Samouraï", aliases: ["the last samurai", "dernier samourai"], search: "A Way of Life Hans Zimmer" },
        { film: "Star Wars", aliases: ["starwars", "star war"], search: "The Imperial March John Williams" },
        { film: "Star Wars", aliases: ["starwars", "star war"], search: "Duel of the Fates John Williams" },
        { film: "Harry Potter", aliases: ["harrypotter"], search: "Hedwig's Theme John Williams" },
        { film: "Jurassic Park", aliases: ["jurassicpark"], search: "Theme from Jurassic Park John Williams" },
        { film: "Indiana Jones", aliases: ["indiana jones", "les aventuriers de l'arche perdue"], search: "Raiders March John Williams" },
        { film: "Les Dents de la Mer", aliases: ["jaws", "dents de la mer"], search: "Theme From Jaws John Williams" },
        { film: "Le Seigneur des Anneaux", aliases: ["lord of the rings", "lotr", "lsda", "seigneur des anneaux"], search: "The Shire Howard Shore" },
        { film: "Game of Thrones", aliases: ["got", "game of throne"], search: "Game of Thrones Ramin Djawadi" },
        { film: "Avengers", aliases: ["avenger", "marvel avengers", "the avengers"], search: "The Avengers Alan Silvestri" },
        { film: "Retour vers le futur", aliases: ["back to the future", "retour vers le futur"], search: "Back to the Future Alan Silvestri" },
        { film: "Forrest Gump", aliases: ["forrestgump", "forrest gump"], search: "Forrest Gump Suite Alan Silvestri" },
        { film: "Oppenheimer", aliases: ["oppenheimer"], search: "Can You Hear The Music Ludwig Goransson" },
        { film: "Rocky", aliases: ["rocky", "rocky balboa"], search: "Gonna Fly Now Bill Conti" },
        { film: "Rocky", aliases: ["rocky", "rocky balboa"], search: "Eye of the Tiger Survivor" },
        { film: "Terminator", aliases: ["terminator"], search: "The Terminator Theme Brad Fiedel" },
        { film: "Mission Impossible", aliases: ["mission impossible"], search: "Mission Impossible Lalo Schifrin" },
        { film: "James Bond", aliases: ["james bond", "007"], search: "James Bond Theme Monty Norman" },
        { film: "Le Bon, la Brute et le Truand", aliases: ["the good the bad and the ugly", "le bon la brute"], search: "The Good The Bad Ennio Morricone" },
        { film: "Titanic", aliases: ["titanic"], search: "My Heart Will Go On Celine Dion" },
        { film: "Matrix", aliases: ["the matrix"], search: "Clubbed to Death Rob Dougan" },
        { film: "Top Gun", aliases: ["topgun"], search: "Danger Zone Kenny Loggins" },
        { film: "Ghostbusters", aliases: ["sos fantomes"], search: "Ghostbusters Ray Parker Jr" },
        { film: "Pulp Fiction", aliases: ["pulpfiction"], search: "Misirlou Dick Dale" },
        { film: "Requiem for a Dream", aliases: ["requiem"], search: "Lux Aeterna Clint Mansell" },
        { film: "Le Fabuleux Destin d'Amélie Poulain", aliases: ["amelie poulain"], search: "Comptine d'un autre été Yann Tiersen" },
        { film: "Kill Bill", aliases: ["killbill"], search: "Battle Without Honor Or Humanity Tomoyasu Hotei" }
    ],
    DISNEY: [
        { disney: "Le Roi Lion", aliases: ["roi lion", "the lion king"], search: "L'histoire de la vie Debbie Davis" },
        { disney: "Le Roi Lion", aliases: ["roi lion", "the lion king"], search: "Je voudrais déjà être roi" },
        { disney: "Aladdin", aliases: ["aladin"], search: "Ce rêve bleu Paolo Domingo" },
        { disney: "Aladdin", aliases: ["aladin"], search: "Prince Ali Richard Darbois" },
        { disney: "La Reine des Neiges", aliases: ["reine des neiges", "frozen"], search: "Libérée délivrée Anaïs Delva" },
        { disney: "Mulan", aliases: [""], search: "Comme un homme Patrick Fiori" },
        { disney: "Tarzan", aliases: [""], search: "Enfant de l'homme Phil Collins" },
        { disney: "Hercule", aliases: [""], search: "Le Gospel Pur" },
        { disney: "Vaiana", aliases: ["moana", "la legende du bout du monde"], search: "Le bleu lumière Cerise Calixte" },
        { disney: "La Petite Sirène", aliases: ["petite sirene", "little mermaid"], search: "Sous l'océan Henri Salvador" },
        { disney: "Le Livre de la Jungle", aliases: ["livre de la jungle", "jungle book"], search: "Il en faut peu pour être heureux Jean Stout" },
        { disney: "Le Livre de la Jungle", aliases: ["livre de la jungle", "jungle book"], search: "Etre un homme comme vous" },
        { disney: "Raiponce", aliases: ["tangled"], search: "Où est la vraie vie" },
        { disney: "Pocahontas", aliases: [""], search: "L'air du vent Laura Mayne" },
        { disney: "La Belle et la Bête", aliases: ["belle et la bete", "beauty and the beast"], search: "Histoire éternelle" },
        { disney: "Le Bossu de Notre-Dame", aliases: ["bossu de notre dame", "hunchback"], search: "Rien qu'un jour" },
        { disney: "Frère des Ours", aliases: ["frere des ours", "brother bear"], search: "Je m'en vais Phil Collins" }, 
        { disney: "Encanto", aliases: [""], search: "Ne parlons pas de Bruno" },
        { disney: "Toy Story", aliases: [""], search: "Je suis ton ami CharlÉlie Couture" },
        { disney: "Coco", aliases: [""], search: "Ne m'oublie pas Coco Andrea Santamaria" },
        { disney: "Lilo et Stitch", aliases: ["lilo & stitch", "lilo and stitch"], search: "Hawaiian Roller Coaster Ride" },
        { disney: "Les Aristochats", aliases: ["aristochats", "aristocats"], search: "Tout le monde veut devenir un cat" },
        { disney: "Blanche-Neige", aliases: ["blanche neige", "snow white"], search: "Un jour mon prince viendra" },
        { disney: "La Princesse et la Grenouille", aliases: ["princesse et la grenouille"], search: "Au bout du rêve" },
        { disney: "Peter Pan", aliases: ["peterpan"], search: "Tu t'envoles" },
        { disney: "Zootopie", aliases: ["zootopia"], search: "Try Everything Shakira" },
        { disney: "Cars", aliases: ["cars 4 roues"], search: "Life is a Highway Rascal Flatts" }
    ],
    RAP: [
        { search: "Orelsan", artist: "Orelsan" }, { search: "Booba", artist: "Booba" }, { search: "PNL", artist: "PNL" },
        { search: "Damso", artist: "Damso" }, { search: "Nekfeu", artist: "Nekfeu" }, { search: "Alpha Wann", artist: "Alpha Wann" },
        { search: "Freeze Corleone", artist: "Freeze Corleone" }, { search: "Kaaris", artist: "Kaaris" }, { search: "SCH", artist: "SCH" },
        { search: "IAM rap", artist: "IAM" }, { search: "Supreme NTM", artist: "Suprême NTM", aliases: ["ntm", "supreme ntm"] },
        { search: "Vald", artist: "Vald" }, { search: "Hugo TSR", artist: "Hugo TSR", aliases: ["hugo (tsr)", "tsr crew"] },
        { search: "Lino Arsenik", artist: "Lino" }, { search: "Despo Rutti", artist: "Despo Rutti" }, { search: "Ninho", artist: "Ninho" },
        { search: "Gazo", artist: "Gazo" }, { search: "Koba LaD", artist: "Koba LaD" }, { search: "Josman", artist: "Josman" },
        { search: "Dinos Punchlinovic", artist: "Dinos", aliases: ["dinos punchlinovic"] }, { search: "Disiz", artist: "Disiz", aliases: ["disiz la peste"] },
        { search: "1995 rap", artist: "1995" }, { search: "Fonky Family", artist: "Fonky Family", aliases: ["ff", "la fonky family"] },
        { search: "Rohff", artist: "Rohff" }, { search: "La Fouine", artist: "La Fouine" }, { search: "Kalash Criminel", artist: "Kalash Criminel" },
        { search: "Niska", artist: "Niska" }, { search: "Gradur", artist: "Gradur" }, { search: "Mac Tyer", artist: "Mac Tyer" },
        { search: "Kery James", artist: "Kery James" }, { search: "Sniper rap", artist: "Sniper" }, { search: "113 rap", artist: "113" },
        { search: "Mafia K'1 Fry", artist: "Mafia K'1 Fry", aliases: ["mafia k1 fry"] }, { search: "Lunatic Booba", artist: "Lunatic" },
        { search: "Sexion d'Assaut", artist: "Sexion d'Assaut", aliases: ["sexion dassaut"] }, { search: "PLK", artist: "PLK" },
        { search: "Ziak", artist: "Ziak" }, { search: "Seth Gueko", artist: "Seth Gueko" }, { search: "Youssoupha", artist: "Youssoupha" },
        { search: "Medine rap", artist: "Medine" }, { search: "Sinik", artist: "Sinik" }, { search: "Diam's", artist: "Diam's", aliases: ["diams"] },
        { search: "Jul rap", artist: "Jul" }, { search: "Werenoi", artist: "Werenoi" }, { search: "Tiakola", artist: "Tiakola" },
        { search: "SDM", artist: "SDM" }, { search: "Maes", artist: "Maes" }, { search: "Alkpote", artist: "Alkpote" },
        { search: "Bosh rap", artist: "Bosh" }, { search: "Niro rap", artist: "Niro" }, { search: "Lomepal", artist: "Lomepal" },
        { search: "Romeo Elvis", artist: "Romeo Elvis" }, { search: "Laylow", artist: "Laylow" }, { search: "Djadja Dinaz", artist: "Djadja & Dinaz" },
        { search: "MC Solaar", artist: "MC Solaar" }, { search: "Gims", artist: "Gims", aliases: ["maitre gims"] }, { search: "Black M", artist: "Black M" },
        { search: "Soprano", artist: "Soprano" }, { search: "Zola rap", artist: "Zola" }, { search: "Leto rap", artist: "Leto" },
        { search: "Heuss l'enfoiré", artist: "Heuss l'Enfoiré" }, { search: "Lorenzo rap", artist: "Lorenzo" }
    ],
    FR: [
        // Focus sur la nostalgie et la pure Variété Française / Chanson Française
        { search: "Georges Brassens", artist: "Georges Brassens" }, { search: "Barbara aigle", artist: "Barbara" },
        { search: "Charles Aznavour", artist: "Charles Aznavour" }, { search: "Jacques Brel", artist: "Jacques Brel" },
        { search: "Edith Piaf", artist: "Edith Piaf" }, { search: "Renaud mistral", artist: "Renaud" },
        { search: "Francis Cabrel", artist: "Francis Cabrel" }, { search: "Jean-Jacques Goldman", artist: "Jean-Jacques Goldman", aliases: ["jjg", "jean jacques goldman"] },
        { search: "Claude Francois", artist: "Claude Francois", aliases: ["cloclo"] }, { search: "Daniel Balavoine", artist: "Daniel Balavoine" }, 
        { search: "Michel Sardou", artist: "Michel Sardou" }, { search: "Johnny Hallyday", artist: "Johnny Hallyday" }, 
        { search: "Joe Dassin", artist: "Joe Dassin" }, { search: "Mylene Farmer", artist: "Mylene Farmer" }, 
        { search: "France Gall", artist: "France Gall" }, { search: "Michel Berger", artist: "Michel Berger" }, 
        { search: "Serge Gainsbourg", artist: "Serge Gainsbourg" }, { search: "Leo Ferre", artist: "Leo Ferre" }, 
        { search: "Georges Moustaki", artist: "Georges Moustaki" }, { search: "Dalida", artist: "Dalida" }, 
        { search: "Christophe aline", artist: "Christophe" }, { search: "Michel Polnareff", artist: "Michel Polnareff" }, 
        { search: "Laurent Voulzy", artist: "Laurent Voulzy" }, { search: "Alain Souchon", artist: "Alain Souchon" }, 
        { search: "Julien Clerc", artist: "Julien Clerc" }, { search: "Maxime Le Forestier", artist: "Maxime Le Forestier" }, 
        { search: "Nino Ferrer", artist: "Nino Ferrer" }, { search: "Sheila francais", artist: "Sheila" }, 
        { search: "Sylvie Vartan", artist: "Sylvie Vartan" }, { search: "Michel Delpech", artist: "Michel Delpech" }, 
        { search: "Alain Bashung", artist: "Alain Bashung" }, { search: "Jacques Dutronc", artist: "Jacques Dutronc" }, 
        { search: "Eddy Mitchell", artist: "Eddy Mitchell" }, { search: "Pierre Bachelet", artist: "Pierre Bachelet" }, 
        { search: "Gilbert Becaud", artist: "Gilbert Bécaud" }, { search: "Claude Nougaro", artist: "Claude Nougaro" },
        { search: "Juliette Greco", artist: "Juliette Gréco" }, { search: "Charles Trenet", artist: "Charles Trenet" },
        { search: "Yves Montand", artist: "Yves Montand" }, { search: "Jean Ferrat", artist: "Jean Ferrat" },
        { search: "Henri Salvador", artist: "Henri Salvador" }, { search: "Bourvil chanson", artist: "Bourvil" },
        { search: "Carlos", artist: "Carlos" }, { search: "Annie Cordy", artist: "Annie Cordy" },
        { search: "Richard Anthony", artist: "Richard Anthony" }, { search: "Dick Rivers", artist: "Dick Rivers" },
        { search: "Celine Dion", artist: "Celine Dion" }, { search: "Indochine", artist: "Indochine" }, 
        { search: "Telephone groupe", artist: "Telephone" }, { search: "Les Rita Mitsouko", artist: "Les Rita Mitsouko", aliases: ["rita mitsouko"] }
    ],
    POP: [
        // Augmentation massive des icônes de la Pop
        { search: "Michael Jackson", artist: "Michael Jackson" }, { search: "Queen", artist: "Queen" }, { search: "The Weeknd", artist: "The Weeknd" }, 
        { search: "Dua Lipa", artist: "Dua Lipa" }, { search: "Daft Punk", artist: "Daft Punk" }, { search: "Bruno Mars", artist: "Bruno Mars" }, 
        { search: "Lady Gaga", artist: "Lady Gaga" }, { search: "Ed Sheeran", artist: "Ed Sheeran" }, { search: "Coldplay", artist: "Coldplay" }, 
        { search: "Rihanna", artist: "Rihanna" }, { search: "Eminem", artist: "Eminem" }, { search: "Gorillaz", artist: "Gorillaz" }, 
        { search: "Beyonce", artist: "Beyonce" }, { search: "Katy Perry", artist: "Katy Perry" }, { search: "Maroon 5", artist: "Maroon 5" }, 
        { search: "Adele", artist: "Adele" }, { search: "Taylor Swift", artist: "Taylor Swift" }, { search: "Justin Timberlake", artist: "Justin Timberlake" }, 
        { search: "Britney Spears", artist: "Britney Spears" }, { search: "Shakira", artist: "Shakira" }, { search: "Madonna", artist: "Madonna" }, 
        { search: "Elton John", artist: "Elton John" }, { search: "David Bowie", artist: "David Bowie" }, { search: "Prince", artist: "Prince" }, 
        { search: "Sia", artist: "Sia" }, { search: "ABBA", artist: "ABBA" }, { search: "The Beatles", artist: "The Beatles" }, 
        { search: "The Rolling Stones", artist: "The Rolling Stones" }, { search: "AC/DC", artist: "AC/DC" }, { search: "U2", artist: "U2" }, 
        { search: "Oasis", artist: "Oasis" }, { search: "Nirvana", artist: "Nirvana" }, { search: "Red Hot Chili Peppers", artist: "Red Hot Chili Peppers" }, 
        { search: "Linkin Park", artist: "Linkin Park" }, { search: "The Black Eyed Peas", artist: "The Black Eyed Peas", aliases: ["black eyed peas"] }, 
        { search: "Justin Bieber", artist: "Justin Bieber" }, { search: "Ariana Grande", artist: "Ariana Grande" }, { search: "Billie Eilish", artist: "Billie Eilish" }, 
        { search: "Harry Styles", artist: "Harry Styles" }, { search: "Miley Cyrus", artist: "Miley Cyrus" }, { search: "Kylie Minogue", artist: "Kylie Minogue" }, 
        { search: "Spice Girls", artist: "Spice Girls" }, { search: "Backstreet Boys", artist: "Backstreet Boys" }, { search: "NSYNC", artist: "NSYNC" }, 
        { search: "Destiny's Child", artist: "Destiny's Child" }, { search: "Avril Lavigne", artist: "Avril Lavigne" }, { search: "Pink", artist: "Pink" }, 
        { search: "Gwen Stefani", artist: "Gwen Stefani" }, { search: "Alicia Keys", artist: "Alicia Keys" }, { search: "Usher", artist: "Usher" }, 
        { search: "50 Cent", artist: "50 Cent" }, { search: "Imagine Dragons", artist: "Imagine Dragons" }, { search: "Charlie Puth", artist: "Charlie Puth" },
        { search: "Shawn Mendes", artist: "Shawn Mendes" }, { search: "The Killers", artist: "The Killers" }, { search: "Muse", artist: "Muse" },
        { search: "Arctic Monkeys", artist: "Arctic Monkeys" }, { search: "Radiohead", artist: "Radiohead" }, { search: "Post Malone", artist: "Post Malone" },
        { search: "Whitney Houston", artist: "Whitney Houston" }, { search: "Mariah Carey", artist: "Mariah Carey" }, { search: "Cher", artist: "Cher" },
        { search: "Cyndi Lauper", artist: "Cyndi Lauper" }, { search: "George Michael", artist: "George Michael" }, { search: "Eurythmics", artist: "Eurythmics" },
        { search: "A-ha", artist: "A-ha", aliases: ["aha"] }, { search: "The Police", artist: "The Police" }, { search: "Ricky Martin", artist: "Ricky Martin" },
        { search: "Jennifer Lopez", artist: "Jennifer Lopez", aliases: ["jlo"] }, { search: "Christina Aguilera", artist: "Christina Aguilera" }, 
        { search: "Kelly Clarkson", artist: "Kelly Clarkson" }, { search: "The Cranberries", artist: "The Cranberries" }, 
        { search: "Alanis Morissette", artist: "Alanis Morissette" }, { search: "Tears for Fears", artist: "Tears for Fears" },
        { search: "Phil Collins", artist: "Phil Collins" }, { search: "Genesis", artist: "Genesis" }, { search: "Bon Jovi", artist: "Bon Jovi" },
        { search: "Aerosmith", artist: "Aerosmith" }, { search: "No Doubt", artist: "No Doubt" }, { search: "Enrique Iglesias", artist: "Enrique Iglesias" }
    ]
};
